#ifndef CNC_RED_ALERT_TD_DISPLAY_CONSTANTS_H_
#define CNC_RED_ALERT_TD_DISPLAY_CONSTANTS_H_

#define ICON_PIXEL_W 24
#define ICON_PIXEL_H 24
#define ICON_LEPTON_W 256
#define ICON_LEPTON_H 256
#define CELL_PIXEL_W ICON_PIXEL_W
#define CELL_PIXEL_H ICON_PIXEL_H
#define CELL_LEPTON_W ICON_LEPTON_W
#define CELL_LEPTON_H ICON_LEPTON_H

//	-----------------------------------------------------------
#define PIXEL_LEPTON_W (ICON_LEPTON_W / ICON_PIXEL_W)
#define PIXEL_LEPTON_H (ICON_LEPTON_H / ICON_PIXEL_H)

#endif  // CNC_RED_ALERT_TD_DISPLAY_CONSTANTS_H_
