#include "tech/key_phrase_hash.h"

#include <cstdint>
#include <string>
#include <string_view>

#include "gtest/gtest.h"

namespace {

TEST(HashKeyPhraseTest, ReproducesRedAlertCodes) {
  // Fixed vectors from the original tables, not generated by HashKeyPhrase.
  const struct {
    std::string_view phrase;
    uint32_t code;
  } cases[] = {
      {"SONY", 0xE0792D6D},          {"ANTHRAXROCKAWAY", 0x90046ECF},
      {"FUNK", 0xC3EE9A26},          {"SLICK", 0xED382178},
      {"JUPITER", 0xA0E2AB53},       {"NATE", 0x00532693},
      {"PASSWORD", 0x7DDFF824},      {"CHEATER", 0x2CB5CF01},
      {"BLUB", 0xB5B63531},          {"ADEN", 0xDFABC23A},
      {"ATEN", 0xDFABC23A},          {"ADUN", 0xDFABC23A},
      {"ATUN", 0xDFABC23A},          {"NUKE", 0x52B19A22},
      {"EARTHIMPROVED", 0xBE79088C}, {"SPOON", 0xB216AE7E},
      {"CARPET", 0x0E07B213},        {"BUILD", 0xA2C09326},
      {"MOBIUS", 0x1F944BB3},        {"CYCLONE", 0xDE07154D},
      {"EDITOR", 0x16B170B1},        {"PLAYTEST", 0xF7DDC227},
      {"FROMINSTALL", 0xD95C68A2},   {"PEROPERO", 0x905F36A5},
  };
  for (const auto& entry : cases) {
    EXPECT_EQ(HashKeyPhrase(entry.phrase), entry.code) << entry.phrase;
  }
}

TEST(HashKeyPhraseTest, ReproducesTiberianDawnCodes) {
  // The phrases documented next to the PARM_ codes in td/defines.h.
  const struct {
    std::string_view phrase;
    uint32_t code;
  } cases[] = {
      {"CROWDED", 0x9CAFC93B},     {"PLAYTEST", 0xF7DDC227},
      {"SUPER", 0x9F38A19D},       {"WIZARD", 0x39D01821},
      {"OBWAN", 0xABDD0362},       {"-EDITOR", 0x7E7C4CCA},
      {"EASY", 0x59E975CE},        {"HARD", 0xACFE9D13},
      {"FROMINSTALL", 0xD95C68A2}, {"TARBOSH", 0xB1A34435},
      {"DANCING", 0x03552894},     {"REMIX", 0x7FDE2C33},
      {"CHARGE!", 0xDC57C4B2},     {"TRANSFORMER", 0x104DF10F},
      {"SERGENT", 0x9E3881B8},     {"PANCAKE", 0x4EA2FBDF},
      {"7TH GRADE", 0xACB58F61},   {"FUNPARK", 0x11CA05BB},
  };
  for (const auto& entry : cases) {
    EXPECT_EQ(HashKeyPhrase(entry.phrase), entry.code) << entry.phrase;
  }
}

TEST(HashKeyPhraseTest, IgnoresAsciiCase) {
  EXPECT_EQ(HashKeyPhrase("pAsSwOrD"), 0x7DDFF824U);
  EXPECT_EQ(HashKeyPhrase("peropero"), 0x905F36A5U);
}

TEST(HashKeyPhraseTest, ReplacesNonPrintingCharacters) {
  // Each non-printing byte becomes 'A' plus its position.
  EXPECT_EQ(HashKeyPhrase("7TH GRADE"), HashKeyPhrase("7THDGRADE"));
  EXPECT_EQ(HashKeyPhrase("\xE9\xFF"
                          "C"),
            HashKeyPhrase("ABC"));
}

TEST(HashKeyPhraseTest, HandlesMaximumLength) {
  const std::string maximum(127, 'A');
  const std::string longer(140, 'A');
  EXPECT_EQ(HashKeyPhrase(maximum), HashKeyPhrase(longer));
}

}  // namespace
