#include "ra/obfuscate.h"

#include <cstdint>
#include <string>

#include "gtest/gtest.h"

namespace {

TEST(ObfuscateTest, ReproducesHistoricalCodes) {
  // Fixed vectors from the original tables, not generated by Obfuscate.
  const struct {
    const char* phrase;
    uint32_t code;
  } cases[] = {
      {"SONY", 0xE0792D6D},          {"ANTHRAXROCKAWAY", 0x90046ECF},
      {"FUNK", 0xC3EE9A26},          {"SLICK", 0xED382178},
      {"JUPITER", 0xA0E2AB53},       {"NATE", 0x00532693},
      {"PASSWORD", 0x7DDFF824},      {"CHEATER", 0x2CB5CF01},
      {"BLUB", 0xB5B63531},          {"ADEN", 0xDFABC23A},
      {"ATEN", 0xDFABC23A},          {"ADUN", 0xDFABC23A},
      {"ATUN", 0xDFABC23A},          {"NUKE", 0x52B19A22},
      {"EARTHIMPROVED", 0xBE79088C}, {"SPOON", 0xB216AE7E},
      {"CARPET", 0x0E07B213},        {"BUILD", 0xA2C09326},
      {"MOBIUS", 0x1F944BB3},        {"CYCLONE", 0xDE07154D},
      {"EDITOR", 0x16B170B1},        {"PLAYTEST", 0xF7DDC227},
      {"FROMINSTALL", 0xD95C68A2},   {"PEROPERO", 0x905F36A5},
  };
  for (const auto& entry : cases) {
    EXPECT_EQ(Obfuscate(entry.phrase), entry.code) << entry.phrase;
  }
}

TEST(ObfuscateTest, IgnoresAsciiCase) {
  EXPECT_EQ(Obfuscate("pAsSwOrD"), 0x7DDFF824U);
  EXPECT_EQ(Obfuscate("peropero"), 0x905F36A5U);
}

TEST(ObfuscateTest, ReplacesNonPrintingCharacters) {
  // Each non-printing byte becomes 'A' plus its position.
  EXPECT_EQ(Obfuscate("7TH GRADE"), Obfuscate("7THDGRADE"));
  EXPECT_EQ(Obfuscate("\xE9\xFF"
                      "C"),
            Obfuscate("ABC"));
}

TEST(ObfuscateTest, HandlesMaximumLength) {
  const std::string maximum(127, 'A');
  const std::string longer(140, 'A');
  EXPECT_EQ(Obfuscate(maximum), Obfuscate(longer));
}

}  // namespace
